### ISSUE TITLE
feat(core): method to expose instance for use in redux-saga and redux-thunk

### ISSUE THREAD

**Issue by jacobfunch** [prescottprue/redux-firestore#13]
I experience issues when fetching data with the get operator.
Works seamlessly when adding data to Firestore though.

Tested on `master` and `v0.1.0-alpha.2` – using `react-redux-firebase` as the base, but since they have made `redux-firestore` optional it's a combination of the two.

`Uncaught (in promise) TypeError: Cannot read property 'collection' of undefined`

Any idea why?

**Comment by prescottprue** [comment]
`redux-firestore` does not yet support using through `getFirebase` from `react-redux-firebase`. This is because `getFirebase` points to the firebase instance that lives on `store.firebase`, which is added by the `reactReduxFirebase` store enhancer.

`reduxFirestore` is the equivalent store enhancer for `redux-firestore`, so that would need its own `getFirestore`, or `getFirebase` will need to be extended.

**Comment by jacobfunch** [comment]
Thank you for a quick reply. Is there another temporary solution than using `withFirestore` or `firestoreConnect`? I really want to make a lookup from within a saga after an action, or I guess can be temporarily from a component. As I understand the other methods require the path on mount, but I need to query after an action is made.

**Comment by prescottprue** [comment]
There are two options:
* use `store.firestore from your redux store by passing `this.context.store.firestore` in the `payload` of the action you `dispatch` to call your saga (make sure you provide `contextTypes`)
* set your own firebase listener and dispatch the `@@react-redux-firebase/SET` action (importable) in the callback so that the data is written into the store

Personally I would go for the first so that it is easy to switch out. That said, I will prioritize getting something out for it (either placing them on `getFirebase` or making a `getFirestore`).

**Comment by prescottprue** [comment]
[`v0.1.0-beta`](https://github.com/prescottprue/redux-firestore/releases/tag/v0.1.0-beta) was released with `getFirestore` in there. Let me know if it does not work as expected.

**Comment by mbraku** [comment]
Using `getFirestore` deosn't seem to be working for me. I'm always getting the "Firebase instance does not yet exist. Check your compose function." error (The error text should probably say "Firestore instance" though, right?)

When looking at the enhancer from `react-redux-firebase` I saw that you're assigning the return value of `createFirebaseInstance` first to `firebaseInstance` and then to `store.firebase` (see https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0/src/enhancer.js#L96).

However, in the `redux-firestore` enhancer you're assigning the return value of `createFirestoreInstance` directly to `store.firestore` without assigning it to `firestoreInstance` first (see https://github.com/prescottprue/redux-firestore/blob/master/src/enhancer.js#L55). 

My guess is that that's the issue I'm facing.

**Comment by karltaylor** [comment]
If anyone came across this, this is working. And you can setup using both `getFirebase` and `getFirestore` by passing in multiple arguments to `applyMiddleware`.

```javascript
const store = createStore(
  rootReducer,
  compose(
    applyMiddleware(thunk.withExtraArgument({ getFirebase, getFirestore })),
    reactReduxFirebase(firebase, {
      userProfile: 'users',
      enableLogging: false
    }),
    reduxFirestore(firebase),
    ...enhancers
  )
)
```

and within your thunk:

```javascript
export default function foo () {
  return function (dispatch, getState, { getFirebase, getFirestore }) {
    const firebase = getFirebase()
    const firestore = getFirestore()
    // do some magic thanks to @prescottprue
  }
}
```

**Comment by dmcshehan** [comment]
Hello everyone,
I have noticed that we gan get a firestore instance like this with `react-redux-firebase`

```javascript
const firestore = getFirebase().firestore();
```

Can't we use this method?

**Comment by prescottprue** [comment]
@dmcshehan that is the method works great if you are using a version which has a store enhancer (i.e. `reduxFirestore`) - the newer versions do not currently include that

**Comment by davidohlin** [comment]
> @dmcshehan that is the method works great if you are using a version which has a store enhancer (i.e. `reduxFirestore`) - the newer versions do not currently include that

@prescottprue how would I go about doing that in the new version? I'm trying to access `getFirestore` in an async action creator, but getting `Error: Firebase instance does not yet exist. Check your compose function`. 

@karltaylor solution earlier in this issue also includes using `reactReduxFirebase` which, if I understand correctly, does not exist in ^3.0.0.

**Comment by prescottprue** [comment]
@davidohlin Did you try `getFirebase`? You should be able to get `getFirebase().firestore()` though it isn't the enhanced methods that dispatch actions.

Going to look into the issue with getFirestore since there [was also an issue in react-redux-firebase that mentioned it wasn't working as expected](https://github.com/prescottprue/react-redux-firebase/issues/785)

**Comment by davidohlin** [comment]
fre 25 okt. 2019 kl. 19:57 skrev Scott Prue <notifications@github.com>:

**Comment by davidohlin** [comment]
@prescottprue Yes, `getFirebase().firestore()` works, I'll use that for now. Thank you!
