### ISSUE TITLE
[QUESTION]: How to add  another doc to the state in firestore.data using @@reduxfirestore/GET_REQUEST without overwritting what is already there.

### ISSUE THREAD

**Issue by Wgil** [prescottprue/redux-firestore#220]
Hello,

I have a collection called `users` with all my users in it and the following queries:
`firestore.get({ collection: 'users',  doc: user1.id })`
`firestore.setListener({ collection: 'users',  where: ['teamId', '==', teamId]  })`

Now what happens is that I send the request for `user1` first, then set the listener, then I get the listener response, which gives me `ordered.users` populated with all the users, and only then do I get success for my first request so `oredered.user` is overwritten with `user1` and the other ones are erased.

Is there a way for me to merge all the data under `ordered.users` instead of overwriting it?

Thanks in advance, any help would be appreciated!

**Comment by prescottprue** [comment]
It may be best to use `storeAs` in the meantime to store your data in different locations of redux state.

Whether to merge state or not is actually a constant source of contention since there are times where this would be advantageous as you mentioned, but others situation, such as [#45](https://github.com/prescottprue/redux-firestore/issues/45) where it caused unexpected results.

Going to leave this open since it is a common question

**Comment by jbtheard** [comment]
Hi,
Perhaps as an optional argument in version 1 ?

**Comment by prescottprue** [comment]
I think the best practice is to leave this to a state selector or other logic when pulling out of redux state from the multiple locations.

That said, I'm open to a PR or a suggestion for how to work this in if anyone has a proposal. Closing for now
