### ISSUE TITLE
feat(query): support for collectionGroup query

### ISSUE THREAD

**Issue by yevgenypats** [prescottprue/redux-firestore#221]
**What is the feature?**

Firestore introduced Collection Group not long ago which gives the power to query collection with same name but not the same pass which is a very very powerful feature.

https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

Is this on the roadmap? or maybe it is supported out of the box?

Cheers

**Comment by yevgenypats** [comment]
@prescottprue I know you are busy. Do you have any timeline for this? or maybe some direction of how to implement this so I would try and take a look?

**Comment by prescottprue** [comment]
@yevgenypats I am pretty busy currently, so it may be a little bit before I get the chance to implement it. That said, including support for this should hopefully be as simple as:
  1. [adding to the firestoreRef util that builds a query from the meta object](https://github.com/prescottprue/redux-firestore/blob/master/src/utils/query.js#L115)
  1. [adding to the getQueryName util that is used to create a key for identifying the query](https://github.com/prescottprue/redux-firestore/blob/master/src/utils/query.js#L198)

If you get something going I would be happy to test it, otherwise, I'll post an update here if/when I get a chance to work on it.

**Comment by yevgenypats** [comment]
solved by https://github.com/prescottprue/redux-firestore/pull/233. closing.
