### ISSUE TITLE
UPDATE_SUCCESS not updating the data reducer

### ISSUE THREAD

**Issue by compojoom** [prescottprue/redux-firestore#82]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
We have 3 filtered views. When the page loads the user is presented with the first tab where we are filtering on state == 0 and we have a pagination.

The user is able to change the state to 1, then the UI should update and the item should be removed.

We use the update function and we are seeing 2 actions.
UPDATE_REQUEST
UPDATE_SUCCESS

the arguments for update_success show state == -1, but the actual data state doesn't change.
Once we get the UPDATE_SUCCESS a LISTENER_RESPONSE is dispatched and we get new items for the list. The problem here is that since our listener looks only for state == 0 and our changed item has state 1 - it's no longer in the LISTENER_RESPONSE and this item never gets modified in the state. So our UI still displays it. 

**What is the expected behavior?**
UPDATE_SUCCESS - should update the item in the data reducer.

I looked at the code and see that you don't use UPDATE_SUCCESS in the data reducer? Why? Aren't we interested in single UPDATE_SUCCESS actions? Are we supposed to manually handle this in our reducers?

**Comment by prescottprue** [comment]
So it seems like you do not have a listener attached at that path? Something that has been unclear so far is if folks are expected updates to happen in state even if they do not have listeners attached, in this case, that seems like what you are asking for.

The answer to your question of why `UPDATE_SUCCESS` is not in the reducer is that most have a listener attached which updates state, and that action type was being dispatched mostly to keep things standard (dispatch action before/after each method call). That said, I do like the idea of having it update state, then if that is not wanted, we could have a `skipDispatch: true` option or something along those lines.

**Comment by prescottprue** [comment]
Just as previously mentioned, when adding `UPDATE_SUCCESS` case to the `dataReducer` causes multiple updates in the case of a listener being attached. If updates from the listener are ignored then changes made outside of the client would not be propagated to state.

It seems like deep equals comparison on the document may be the only real way to make it work in both cases. Even with that, we still have the issue of not overwriting subcollections which may be on the document already.

Since there are questions still up in the air about this, I'm going to move forward with the `0.4.0` release and we can look at addressing this in an upcoming release.

**Comment by compojoom** [comment]
Well, yea. i haven't noticed that up until now, because in my current use cases if i had a list, to update a single list item - I always had a new view - which directly listens to this document. So updates here are propagated to the store.

But in this particular case we have a list with items and we are updating the items in the list - without attaching listeners to the documents themselves. If we didn't filter the data in any way my guess is that we wouldn't see this issue, as the LiSTENER_RESponse on the collection would have the update.

**Comment by jcmandersson** [comment]
Hey! I have the same problem. How did you decide to solve it?

**Comment by compojoom** [comment]
@jcmandersson - can you use the ordered reducer? I think that the items there are getting updated correctly.

**Comment by jcmandersson** [comment]
You are correct, thank you!

**Comment by scramblor** [comment]
@prescottprue Was it ever decided to have methods update local state on add/update state without attaching a listener? Seems excessively chatty to have 1-2 extra reads when you do a write if you aren't expecting any external changes to your firestore.

Maybe this could be opt in/out behavior if it complicates interactions with the listeners. I don't think there would be any scenarios where you would want to enable both.

I also think the docs around add/update could be clarified to explicitly say local state won't be updated without a listener.

**Comment by prescottprue** [comment]
@scramblor Still looking to decide that for v1.0.0, so I'm really glad you reached out to remind me. I'll add a not about this to the [v1.0.0 Roadmap wiki](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap).

My current feelings are that it would be best to have the default set so that add/update calls do not update state unless you have a listener attached, but there is an option to turn it on.

A while ago I had thoughts around a "smart" way of doing this by applying add/update changes only if a listener is not attached (by actually checking attached listeners), but it seemed to be a bit complex. I avoided this route since it is nice to keep reducers simple, but it might be worth looking into?

**Comment by scramblor** [comment]
@prescottprue My gut feeling is that someone will want either a listener attached or add/update calls updating redux state. I'm not sure if there are situations where you would want both behaviors or neither. With that in mind having a "smart" way would be great from a user perspective but may not be worth the internal implementation complexity, seems like there may be a lot of edge cases to account for.

If you end up going the simple route, where were you thinking to configure the behavior? Having an additional parameter on the add/update methods would give a user a lot of granularity over behavior.

**Comment by prescottprue** [comment]
@scramblor "One or the other" is what I was trying to say in my last post, but now that I re-read it, I see that is kinda unclear. Glad we agree though.

The option being passed to add/update sounds like a good plan
